# Generated by Django 3.0.5 on 2020-07-20 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('drug_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=255)),
            ],
        ),
    ]
