# Generated by Django 3.0.5 on 2020-07-26 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='patientSymptomsDiseaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptom_name', models.CharField(max_length=255)),
                ('disease_name', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('pAdharNumber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctor.patientModel')),
            ],
        ),
        migrations.RemoveField(
            model_name='patientsymptomsmodel',
            name='pAdharNumber',
        ),
        migrations.DeleteModel(
            name='patientDiseasesModel',
        ),
        migrations.DeleteModel(
            name='patientSymptomsModel',
        ),
    ]
