# Generated by Django 3.0.5 on 2020-07-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='mobileNumber',
            field=models.CharField(max_length=15),
        ),
    ]
