# Generated by Django 3.0.5 on 2020-07-20 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20200720_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmodel',
            name='adharNumber',
            field=models.BigIntegerField(),
        ),
    ]
