# Generated by Django 3.0.5 on 2020-07-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_patientmedicinemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientmedicinemodel',
            name='aft',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='patientmedicinemodel',
            name='mor',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='patientmedicinemodel',
            name='nit',
            field=models.CharField(default='null', max_length=255),
        ),
    ]
