# Generated by Django 3.0.5 on 2020-07-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20200726_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='extendeduser',
            name='aboutMe',
            field=models.CharField(default='null', max_length=10),
            preserve_default=False,
        ),
    ]
