# Generated by Django 3.0.5 on 2020-08-07 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_auto_20200730_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientmedicinemodel',
            name='count',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='patientmedicinemodel',
            name='status',
            field=models.CharField(default='null', max_length=50),
        ),
    ]
